### ISSUE TITLE
request feeder file

### ISSUE THREAD

**Issue by logicminds** [chef-partners/vmware-vra-gem#20]
I wrote some wrapper code around this gem to take in a file that contains all the necessary request data

Example:

```yaml
vra_blueprint_requests:
  - oracle_test_vm1:
      catalog_item_id: a9cd6148-6e0b-4a80-ac47-f5255c52b43d
      catalog_item_name: 'Oracle_system'  # in case the ids change per environment
      properties:
        cpus: 2
        memory: 4096
        requested_for: "devmgr@corp.local"
        lease_days: 3
      parameters:
        my_parameter:
          type: 'string'
          value: 'my value'

```

Snippet of wrapper code
```ruby
def create_request(name, request_data)
  logger.info("Creating request for #{name}")
  # convert keys to symbols
  properties = Hash[request_data['properties'].map{|(k,v)| [k.to_sym,v]}]
  parameters = request_data['parameters']
  item_id = request_data['catalog_item_id']
  catalog_request = vra.catalog.request(item_id, properties)
  # need to further set the properties
  parameters.each do | p_name, p_values |
    catalog_request.set_parameter(p_name, p_values['type'], p_values['value'])
  end
  request = catalog_request.submit
end

# creates requests based on a request file that is fed into this script
def create_requests(properties_file)
  request_data = YAML.load_file(properties_file)
  request_data['vra_blueprint_requests'].map do | data |
    item_name = data.keys.first
    item_data = data.values.first
    create_request(item_name, item_data)
  end
end

create_requests(properties_file)


```

If this is useful to anyone I can make a PR.
